services:
  todo-service:
    host: todo-service
    port: 8082

db:
  host: mysql
  port: 3306
  username: root
  password: password
  schema: ${db.name}

todo-service:
  ribbon:
    listOfServers: ${services.todo-service.host}:${services.todo-service.port}

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://${db.host}:${db.port}/${db.schema}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.int}

logging:
  level:
    org:
      springframework:
        security: INFO





server:
  port: ${services.${spring.application.name}.port}
